name: CI

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: GCP Login Credentials
        run: |
          echo Logging into GCP...
          echo Status of authorization.

      - name: Tests
        run: |
          echo Here we will run some tests,
          echo Results of the tests.

      - name: Building Docker Image
        run: |
          echo Building Docker Image with version tag...

      - name: Push Docker Image to Artifact Registry
        run: |
          echo Pushing Docker Image to Artifact Registry with tags: commit and latest

      - name: Deploy applicaton to GCP Cloud Run
        run: |
          echo Deploying to Cloud Run
